### PR TITLE
Use the same header in published scan as the published cloud

### PR DESCRIPTION
**Pull request by MikHut**
Thought it might make sense for these to match since they came from the same incoming data, also uses the data timestamp instead which might be useful. Happy to discuss or make changes upon request.

### CODE REVIEW

**Comment by MikHut** [comment]
Seems to match #37, although that didn't end up in the noetic branch.

**Comment by Darkproduct** [comment]
We just cam across the same issue. This was fixed in #37 and then reverted back [here](https://github.com/iralabdisco/ira_laser_tools/commit/2bf6a10da9ada0fc09c955c8ddb2781529fd0214#r56979765) for some unknown reason. The timestamps are really important if you do any kind of sensor fusion, or would like to have sanity checks in critical applications like amcl. 

This will fix #36 as well.

Thanks @MikHut and @hcostelha for the pull-requests.

**Comment by JackFrost67** [comment]
> The timestamps are really important if you do any kind of sensor fusion, or would like to have sanity checks in critical applications like amcl.

I'm wondering if this should be as you say, or it is a special use case. What's the problem, I mean, how the timestamps affect the output of your project.
Anyway, thanks for the support.

**Comment by MikHut** [comment]
> > The timestamps are really important if you do any kind of sensor fusion, or would like to have sanity checks in critical applications like amcl.
> 
> I'm wondering if this should be as you say, or it is a special use case. What's the problem, I mean, how the timestamps affect the output of your project.
> Anyway, thanks for the support.

I think it makes sense for the timestamps to match the original data source, unless there is a use case I am not thinking of. For localisation in particular (or any other sensor fusion involving time), you would definitely want the timestamp of the original data so that you can work out how much you have moved since the data was taken.

**Comment by JackFrost67** [comment]
Apology my mistake, i'm gonna merge, make some changes to the repository and then update the release

**Comment by MikHut** [comment]
Thanks @JackFrost67 🙂

**Pull request merged**
