### PR TITLE
Patching topic, timing, and field issues

### PR DESCRIPTION
**Pull request by ruffsl**
- Simplifying topic subscription and making more predictable
- Using latest measurement's for time stamp for publishing
- Converting just distance to avoid PCL field mismatch
  See commit comments for details

### CODE REVIEW

**Comment by trigal** [comment]
Thx for the pull-request. I will check everything in mid-january after finishing my phd thesis :-)

**Review by trigal — APPROVED** [review]
LGTM

**Review by trigal — CHANGES_REQUESTED** [review]
"no fancy filtering topics, trusting the user to correctly list the topic" 

I can't really "trust" all the users of our vehicle so I can't accept this part of the code. However we can improve the issue "This originally didn't play nice with a slow gazebo startup" by waiting for all the topics, using something like http://docs.ros.org/api/roscpp/html/namespaceros_1_1topic.html

?

**Comment by ruffsl** [comment]
> by waiting for all the topics

For ROS1, I think it would be ill-advised to incorporate any stateful startup process for topic activity, such as waiting for them to register with the master with callbacks, given ROS1 has very little in the way of node lifecycle management.

**Pull request closed without merging**
